/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package software.eng.assignment.app;

import software.eng.assignment.list.LinkedList;

import static software.eng.assignment.utilities.StringUtils.join;
import static software.eng.assignment.utilities.StringUtils.split;
import static software.eng.assignment.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}

